### ISSUE TITLE
[Bug] Character Collections sometimes do not load upon teleporting

### ISSUE THREAD

**Issue by thetrueyoshifan** [xivdev/Penumbra#41]
When entering new zones, character collections sometimes do not load for the player character. This seems to happen most frequently when loading into housing areas (in this particular case, The Lavender Beds). Putting on or taking off a piece of gear seems to cause the mods to load in correctly afterwards. This also seems to happen upon taking Aethernet teleports to different zones, but it does not happen when using the Aethernet to go between shards in the same zone.

In the debug log, it does appear that Penumbra tries to redraw the character, but it doesn't seem to work.

(side note, this also happened one of the times I came through the Aethernet. I've had this before with older builds of Penumbra though, so it's most likely not related to this issue)
![ffxiv_dx11_VI52lUw7IF](https://user-images.githubusercontent.com/42860543/126119281-8ba0b383-c0dc-4301-97bb-d6108bc3791e.jpg)

**Comment by Ottermandias** [comment]
I assume that's happening when it tries to reload the character too early before it is drawn by the game itself. Maybe I need to put in a delay after zone changes or something. Didn't happen for me though, maybe dependant on duration of loading screens?

The bodyless people are probably starting to get loaded in asynchronosly while your settings are changed for some specific character and wearing something that is changed - then the .mdl gets loaded, the collection changes back, and the mdl doesn't have the appropriate .mtrl and .tex files. I had that happen a few times but I don't think I can prevent that for now.

In both cases a manual /penumbra redraw <s>  and /penumbra redraw <t>  should fix that problem though :)

**Comment by DevJinnial** [comment]
Yeah it's pretty hit or miss for me with this issue. Doesn't happen often but I've got the command bound to a QoL Toolbar button to make it easier to redraw.

**Comment by DevJinnial** [comment]
Wanted to make note of this as I believe it might be related. Character collections are not loaded upon entering and exiting cutscenes in praetorium. Not sure if this should be it's own issue or if it should go under this or the gpose task so I'll leave it here for ya @Ottermandias

**Comment by Ottermandias** [comment]
I check transition flags now before reloading an actor, this seems to have helped a great deal at stabilizing map changes for me. Keeping this open for now until a new release / you guys had time to test it yourself etc.

**Comment by thetrueyoshifan** [comment]
Currently testing with the latest commits to master, and the issue of loading into housing areas and using Aethernet is still an issue. As for the cutscene and GPose issue, I have a potential solution. More to follow in that issue though, as I believe it's unrelated to this one.

**Comment by Ottermandias** [comment]
If this is still a problem with the customizable delay in loading, I'm afraid I have no idea how to do it better.

**Comment by steponmepls** [comment]
It just happened to me as well. I'm currently using latest build. I made a collection for my own character and mods are only loaded partially. I set meta changes like body model in default and character specific changes like changes for certain items in a collection made for my own character but things seem to be load only partially or not at all depending if I enter new instances, get past a warp line, teleport or open the character menu.

The mod list for default is:

- Boots/shoes modpack which contains a lot of model changes (priority 0)
- Body model change (priority 1)

and the list for my own character is:

- Item model change for werewolf head (priority 0)
- Teeth model change (priority 0)

https://user-images.githubusercontent.com/63500907/130272246-8cf905cb-4410-4665-a55b-3e97f35625c1.mp4

**Comment by Ottermandias** [comment]
Increase the customizable delay in advanced options. I don't know anything else I can change at the moment.

**Comment by steponmepls** [comment]
I fixed the missing feet issue by also setting `Forced` to `Default` instead of `None` because I misunderstood the mutual exclusivity of `Default Collection` and any other character-specific collections. I don't know why the model isn't loading properly in character menu though
