### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Issacar13** [xivdev/Penumbra#489]
There was an update about 15mins ago, since I updated Penumbra game crashed 3 times in that span of time. After the 3rd time I turned off penumbra and my game stopped crashing.

Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF70D73678A
Parameters: 0, FFFFFFFFFFFFFFFF
Call Stack
{
  [0]	ffxiv_dx11.exe+3D678A	(sub_1403D6750+0x3A)
  [1]	ffxiv_dx11.exe+3D678A	(sub_1403D6750+0x3A)
  [2]	ffxiv_dx11.exe+3D668A	(sub_1403D6530+0x15A)
  [3]	ffxiv_dx11.exe+3D646F	(sub_1403D6400+0x6F)
  [4]	ffxiv_dx11.exe+3D8B0F	(Client::Graphics::Kernel::Device::ImmediateContextDX11.ProcessCommands+0x2F)
  [5]	ffxiv_dx11.exe+3D9942	(Client::Graphics::Kernel::Device::RenderThread.Run+0x52)
  [6]	ffxiv_dx11.exe+1DF690	(sub_1401DF670+0x20)
  [7]	ffxiv_dx11.exe+1CC4AB6	(unknown_libname_2295+0x5A)
  [8]	KERNEL32.DLL+2E8D7	(BaseThreadInitThunk+0x17)
  [9]	ntdll.dll+3C34C	(RtlUserThreadStart+0x2C)
}

Registers
{
  RAX:	1829128FD28 [ffxiv_dx11.exe+2013180	(vtbl_Client::Graphics::Kernel::PixelShader)]
  RBX:	4000000000000000
  RCX:	1829039B170 [ffxiv_dx11.exe+2013710	(vtbl_Client::Graphics::Kernel::Device::ImmediateContextDX11)]
  RDX:	18294AAC850
  R8:	E
  R9:	18291AB9580 [ffxiv_dx11.exe+2013658	(vtbl_Client::Graphics::Kernel::DeviceDX11)]
  R10:	0
  R11:	2948BFFD68 [ffxiv_dx11.exe+3D646F	(sub_1403D6400+0x6F)]
  R12:	1
  R13:	18297D3DB38 [18297D3DB40]
  R14:	18297D3DB38 [18297D3DB40]
  R15:	1829039B170 [ffxiv_dx11.exe+2013710	(vtbl_Client::Graphics::Kernel::Device::ImmediateContextDX11)]
  RSI:	E
  RDI:	18294AAC850
  RBP:	0
  RSP:	2948BFFCB0 [182949E3DA0]
  RIP:	ffxiv_dx11.exe+3D678A	(sub_1403D6750+0x3A)
}

Stack
{
  [RSP+0]	182949E3DA0 [1C50578E5C0]
  [RSP+8]	1
  [RSP+10]	0
  [RSP+18]	ffxiv_dx11.exe+3D668A	(sub_1403D6530+0x15A)
  [RSP+20]	4
  [RSP+28]	182948CA95C [FFFF00001C000007]
  [RSP+30]	182948CAA10 [1C4D4B40900]
  [RSP+38]	1
  [RSP+40]	0
  [RSP+48]	ffxiv_dx11.exe+3D668A	(sub_1403D6530+0x15A)
  [RSP+50]	2
  [RSP+58]	18294AAC6FC [FFFF00001C00000D]
  [RSP+60]	18294AAC7A0 [18294AAA820]
  [RSP+68]	59A
  [RSP+70]	0
  [RSP+78]	0

**Comment by Chapien** [comment]
Are you on Windows 11 or using Wine/Proton on Linux? Both are known to crash with Penumbra from time to time. I suspect the reasons might be the same, to be honest; whatever the problem is must have something to do with Windows APIs, and Penumbra was just "getting lucky" so to speak that it wasn't an issue except for on Wine (well, until Win11)

**Comment by Theo-Asterio** [comment]
This was already resolved in discord. Also no, Windows 11 isn't "known to crash" that is very much a lie. Wine/Proton is partially due to hooking in Dalamud but even then, there's a thread on that which seems to be mostly resolved with stg changes in Dalamud.

**Comment by Chapien** [comment]
> This was already resolved in discord. Also no, Windows 11 isn't "known to crash" that is very much based on no information. Wine/Proton is partially due to hooking in Dalamud but even then, there's a thread on that which seems to be mostly resolved with stg changes in Dalamud.

I m ay be misremembering the Win11 issues (they could have been something else). That said, I am aware that the current staging Dalamud seems to have fixed these issues.

**Comment by Theo-Asterio** [comment]
> can we get a rundown here for what the fix was?
>
No, if you have an issue it would be better for you to visit the discord and provide your information there. It's very unlikely you have the same issue given Dalamud changes have happened. If you can't access the discord, highly suggest resolving that as it's impossible to identify your potential issue without information.

**Comment by MaeveRose** [comment]
Well. i don't have access to the discord. i've tried about 20 times, but i cannot accept the invite.

**Comment by Cilsor** [comment]
> Nothing is wrong with the invite link, very much can't troubleshoot why you can't join there. Once you get there you need to read the channels as well but again no information means no troubleshooting.

I've actually had this issue. What it comes down to is branches of firefox / waterfox / etc wont pass the session cookie around properly if the user has any combination of adblockers enabled. Even if those adblockers are suspended, it still doesn't work. I had to temporarily change my default browser to chrome and deal with accepting the invite that way, then return my default to waterfox. 

I'm having the same crashes as the OP on windows 10. I suppose I'll join to discord to find the resolution, too.
